### ISSUE TITLE
Error launching run.cmd

### ISSUE THREAD

**Issue by Skitoris** [jhriverasa/wakfu-farmscript#2]
I get this error: 

Traceback (most recent call last):
  File "C:\Users\XXXXX\Downloads\wakfu-farmscript-main\FarmScriptGUI.py", line 3, in <module>
    import guiElements
  File "C:\Users\XXXXX\Downloads\wakfu-farmscript-main\guiElements.py", line 13, in <module>
    sg.Combo(
TypeError: Combo.__init__() got an unexpected keyword argument 'expand_x'

**Comment by jhriverasa** [comment]
@Skitoris  Seems like a bug related to PySimpleGUI package could you install the specific version ?  
`pip install PySimpleGUI==4.60.4`

**Comment by Skitoris** [comment]
Works great now! Thanks for the advice!
